INSERT INTO ROLE VALUES(1,'ROLE_ADMIN')
INSERT INTO ROLE VALUES(2,'ROLE_USER')

INSERT INTO USER VALUES(1,'airrudi@hotmail.com','rc','1A')
INSERT INTO USER VALUES(2,'piet@hotmail.com','piet','2A')

INSERT INTO LOGIN VALUES(1,TRUE,1,'rc',2,1)
INSERT INTO LOGIN VALUES(2,TRUE,'piet','piet',2,1)